### PR TITLE
bump amplify_num to 0.4.0

### PR DESCRIPTION
**Pull request by 6293**

### CODE REVIEW

**Comment by 6293** [comment]
@dr-orlovsky please publish amplify_num 0.4.0 and amplify 3.12.0. Build is failing because amplify_apfloat cannot find amplify_num 0.4.0 for now.

**Comment by dr-orlovsky** [comment]
Ok, I will be able to do that this evening. Will write here once it will be done

**Comment by 6293** [comment]
Actually we should bump amplify to 3.12.0 after amplify_apfloat 0.1.0 is published (otherwise we have to re-bump amplify to 3.13.0 to include amplify_apfloat). If you hate back and forth, you can add me to the maintainer and I will do it for you

**Comment by dr-orlovsky** [comment]
I need CI to succeed in order to be merged (it is controlled by repo policies). Closing this in favor of https://github.com/LNP-BP/rust-amplify/pull/121 (I also fixed missed exports there)

**Comment by dr-orlovsky** [comment]
Released all packages

**Pull request closed without merging**
