### PR TITLE
issue-78. DivRem trait added to smallint, bigint

### PR DESCRIPTION
**Pull request by josediegorobles**
Hi, this is the corrected versión with only one commit.

### CODE REVIEW

**Comment by josediegorobles** [comment]
We have duplicate a method:

// same operation as in div_rem, not panicking when division by zero
            #[inline]
            fn div_rem_checked(self, other: Self) -> Option<(Self, Self)> {
                match other {
                    Self::ZERO => None,
                    _ => Some(self.div_rem(other)),
                }
            }

in smallint and bigint. Maybe the best is that it is implemented in the trait, but then we need ZERO it's in some trait.

**Comment by dr-orlovsky** [comment]
Looks good to me. We need to fix the formatting by running `cargo fmt --workspace` in the project root - and rebase on master where I've fixed an issue emerged with the last rust nightly

**Comment by josediegorobles** [comment]
> Looks good to me. We need to fix the formatting by running `cargo fmt --workspace` in the project root - and rebase on master where I've fixed an issue emerged with the last rust nightly (see #98)

I make the two changes.
Cargo fmt --workspace said me "Found argument '--workspace' which wasn't expected, or isn't valid in this context" so i push with cargo fmt changes, is it ok?

**Comment by dr-orlovsky** [comment]
Probably it will not work, let's see what CI will say. If CI will fail, try doing `cargo fmt --all` instead

**Comment by josediegorobles** [comment]
> Probably it will not work, let's see what CI will say. If CI will fail, try doing `cargo fmt --all` instea

It passed 13 checks. 
I used cargo fmt --all and there aren't any changes, so I think it's ok.
I could see that code coverage is down, so maybe I have to do the test then?

**Comment by dr-orlovsky** [comment]
Yes, tests will be definetly appreciated!

**Comment by josediegorobles** [comment]
> Yes, tests will be definetly appreciated!

Ok, so i Will make a new commit with the tests

**Comment by dr-orlovsky** [comment]
Also pls rebase once more onto master since I merged couple of changes there and there are new CI tests which will not pass without updating the tip

**Comment by josediegorobles** [comment]
> Also pls rebase once more onto master since I merged couple of changes there and there are new CI tests which will not pass without updating the tip

Now appears to be correct

**Comment by dr-orlovsky** [comment]
Merged and published new version. Thank you!

**Pull request merged**
