### PR TITLE
WASM in CI

### PR DESCRIPTION
**Pull request by cryptoquick**
- [x] Add wasm-pack and wasm32 target to lint and test in CI.
- [x] Add caching to most actions to speed up CI builds.
- [x] Add features needed for wasm-pack to compile to headless chrome.

This PR does not_resolve #143, but it provides the tooling necessary to debug the issues.

### CODE REVIEW

**Comment by cryptoquick** [comment]
Hm, this PR is actually not running my CI workflow, so I can't test it. Not sure what to do here. Maybe I have to added as a developer to the repo?

**Comment by cryptoquick** [comment]
@dr-orlovsky Please also see if this is okay:
https://github.com/cryptoquick/rust-amplify/pull/1

I did that because of the error in the linter test:
https://github.com/rust-amplify/rust-amplify/actions/runs/3190687266/jobs/5206524255#step:5:63

**Comment by dr-orlovsky** [comment]
I see. Since we can't update edition (pls see rationale in that PR), we have to restrict the max `one_cell` version to the one before edition upgrade. In fact it is a failure of `once_cell` maintainers which introduced 2021 edition (which is a breaking change) without major version bump

**Comment by cryptoquick** [comment]
This apparently blew up in a discussion in the `once_cell` crate, but I found this:
https://github.com/matklad/once_cell/issues/201#issuecomment-1258808649
Can you try re-running my CI actions again?

**Comment by cryptoquick** [comment]
Thanks! Looks like the things I'd expect to fail on wasm to fail, except the desktop clippy lints, which I believe found legitimate issues... Can this be merged, then?

**Comment by cryptoquick** [comment]
Awesome!

**Pull request merged**
